function c = constants()
c = struct(                             ...
    'config_set_name', 'SlxpyCodegen', ...
    'model_config_name', 'model.toml',  ...
    'metadata_version', '1.0.0',        ...
    'metadata_name', 'metadata.json',   ...
    'model_dir', 'model',               ...
    'meta_workdir_key', 'SlxpyWorkdir', ...
    'tp_compat_suffix', '__compat__',   ...
    'simscape_source_prefix', {{
        'ex'        % common\external\library\c\<arch>, 29
        'pm'        % common\foundation\core\c\<arch>, 5
        'mc'        % common\math\core\c\<arch>, 106
        'ssc_core'  % simscape\engine\core\c\<arch>, 125
        'ssc_sli'   % simscape\engine\sli\c\<arch>, 48
        'ssc_st'    % simscape\simtypes\core\c\<arch>, 2
        'sm'        % sm\core\c\<arch>, 50
        'pm_math'   % sm\math\c\<arch>, 37
        'sm_ssci'   % sm\ssci\c\<arch>, 4
    }}                                  ...
);
end

function pat = make_ssp(prefix)
pat = ['^' prefix '_[0-9a-f]{8}.c$'];
end
